### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'bad'

### ISSUE THREAD

**Issue by hsm4703** [mikegsrv/csv2xml#1]
E:\csv2xml-master>python csv2xml.py label1.csv Image/ contert_data/
Traceback (most recent call last):
  File "csv2xml.py", line 67, in <module>
    data = convertRow(row, folder, width, height)
  File "csv2xml.py", line 61, in convertRow
    </annotation>""" % (r[0],f,w, h, r[5], r[1], r[2], int(r[1]) + int(r[3]), int(r[2]) + int(r[4]))
ValueError: invalid literal for int() with base 10: 'bad'

**Comment by mikegsrv** [comment]
Hello! 

Can you, please, provide an example of your CSV and input images structure? 
Please, note, that this converter was made for RTSD-dataset only and cannot be used on datasets with another folder structure.

Thank you in advance.

Best regards,
Mikhail

**Comment by hsm4703** [comment]
![1601870973944](https://user-images.githubusercontent.com/42968054/95039533-a0dbfc80-0703-11eb-95d7-7e04865109a1.jpg)

**Comment by hsm4703** [comment]
like this  i guess class  ismy problem  how can i change

**Comment by mikegsrv** [comment]
@hsm4703 sorry for the delayed answer.

In order to convert your file you need to change [this string](https://github.com/mikegsrv/csv2xml/blob/ad50b52ed8f45089e4cd90d34e01b9de6a40bb79/csv2xml.py#L55)

As far as I can see, I'm trying to convert 3rd column of a row into integer and you have string.

Please, tell me what kind of output xml you want to receive? 
If I can get any example, I will provide an answer, so that you can test it.|

Best regards,
Mikhail

**Comment by mikegsrv** [comment]
Closed due to no activity in a month. Please, reopen in case you need my assistance.
